### ISSUE TITLE
502 Bad Gateway onlyoffice

### ISSUE THREAD

**Issue by FabMARCHAL** [heyvaldemar/nextcloud-onlyoffice-traefik-letsencrypt-docker-compose#2]
The test https://XXXX/healthcheck reply 502 Bad Gateway and Nextcloud can't comunicate with onlyoffice

Thanks for help

**Comment by heyvaldemar** [comment]
hey @FabMARCHAL,

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
